sonar.projectKey=atm-app
sonar.projectName=atm-app
sonar.sourceEncoding=UTF-8

sonar.sources=backend/src/main/java,frontend/src,k8s,infra,.github
sonar.tests=backend/src/test/java,frontend/tests

sonar.java.binaries=backend/build/classes/java/main
sonar.junit.reportPaths=backend/build/test-results/test
sonar.coverage.jacoco.xmlReportPaths=backend/build/reports/jacoco/test/jacocoTestReport.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/build/**,**/.svelte-kit/**,**/.gradle/**,**/gradle/**,frontend/src/routes/layout.css
sonar.coverage.exclusions=k8s/**,infra/**,.github/**,**/*Application*,frontend/src/app.html,frontend/src/app.d.ts,frontend/src/routes/**,frontend/src/lib/index.ts,frontend/src/lib/form.ts,frontend/src/lib/assets/**

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
