apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend
  namespace: atm-lab3
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - atm-lab3
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
