apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: atm-lab3
  labels:
    app: backend
    app.kubernetes.io/name: backend
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - name: http
      port: 80
      targetPort: 8084
