apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: atm-lab3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # Замени REGISTRY_ID на твой ID реестра в Yandex Cloud
          image: cr.yandex/REGISTRY_ID/atm-backend:lab3
          ports:
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          readinessProbe:
            httpGet:
              path: /api/v1/atm
              port: 8084
            initialDelaySeconds: 25
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/v1/atm
              port: 8084
            initialDelaySeconds: 40
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
